export const // eslint-disable-line one-var
    SET_AUTHENTICATED = 'SET_AUTHENTICATED',
    SET_PRODUCTS = 'SET_PRODUCTS',
    SET_ARTICLES = 'SET_ARTICLES',
    SET_CATEGORIES = 'SET_CATEGORIES',
    SET_SUB_CATEGORIES = 'SET_SUB_CATEGORIES',
    SET_FILTERED_ARTICLES = 'SET_FILTERED_ARTICLES',
    SET_MAIN_SLIDES = 'SET_MAIN_SLIDES',
    SET_PARTNERS = 'SET_PARTNERS',
    SET_SEO = 'SET_SEO',
    SET_ADMINS = 'SET_ADMINS',
    SET_ORDERS = 'SET_ORDERS';
