export const // eslint-disable-line one-var
    SET_AUTHENTICATED = 'SET_AUTHENTICATED',
    SET_PRODUCTS = 'SET_PRODUCTS',
    SET_FILTERED_PRODUCTS = 'SET_FILTERED_PRODUCTS',
    SET_ARTICLES = 'SET_ARTICLES',
    SET_FILTERED_ARTICLES = 'SET_FILTERED_ARTICLES',
    SET_CATEGORIES = 'SET_CATEGORIES',
    SET_PARTNERS = 'SET_PARTNERS',
    SET_FILTERED_PARTNERS = 'SET_FILTERED_PARTNERS';
