export const // eslint-disable-line one-var
    SET_PRODUCTS = 'SET_PRODUCTS',
    SET_LANG_MAP = 'SET_LANG_MAP',
    SET_LANG_ROUTE = 'SET_LANG_ROUTE',
    SET_LANG = 'SET_LANG',
    SET_MEDIA_INFO = 'SET_MEDIA_INFO',
    SET_CATEGORIES = 'SET_CATEGORIES',
    SET_SUB_CATEGORIES = 'SET_SUB_CATEGORIES',
    SET_ARTICLES = 'SET_ARTICLES';
