export const // eslint-disable-line one-var
    SET_PRODUCTS = 'SET_PRODUCTS',
    SET_LANG_MAP = 'SET_LANG_MAP',
    SET_LANG_ROUTE = 'SET_LANG_ROUTE',
    SET_LANG = 'SET_LANG',
    SET_MEDIA_INFO = 'SET_MEDIA_INFO',
    SET_CATEGORIES = 'SET_CATEGORIES',
    SET_SUB_CATEGORIES = 'SET_SUB_CATEGORIES',
    SET_PRODUCTS_CATEGORIES = 'SET_PRODUCTS_CATEGORIES',
    SET_ARTICLES = 'SET_ARTICLES',
    SET_SCROLL_TO_CHARACTERISTIC = 'SET_SCROLL_TO_CHARACTERISTIC',
    SET_PARTNERS = 'SET_PARTNERS',
    SET_BASKET = 'SET_BASKET',
    SET_WISHLIST = 'SET_WISHLIST';
